[package]
name = "raytracing"
version = "0.0.1"
edition = "2021"

[dependencies]
stl = "0.2.1"
ndarray = "0.15.4"
glam = "0.20.2"
image = "0.24.1"

[lib]
name = "raytracing"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"
